name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Update to Node.js 18

    - name: Install dependencies
      run: |
        npm install -g htmlhint stylelint jshint broken-link-checker vnu-jar stylelint-config-standard || {
          echo "Dependency installation failed";
          exit 1;
        }

    - name: Verify Stylelint Configuration
      run: |
        if [ ! -f .stylelintrc.json ]; then
          echo "Creating .stylelintrc.json"
          echo '{
            "extends": "stylelint-config-standard",
            "rules": {
              "indentation": 2,
              "number-leading-zero": "always",
              "string-quotes": "double",
              "block-no-empty": true,
              "color-no-invalid-hex": true,
              "comment-no-empty": true,
              "declaration-block-no-duplicate-properties": true,
              "declaration-block-no-shorthand-property-overrides": true,
              "font-family-no-duplicate-names": true,
              "function-calc-no-unspaced-operator": true,
              "keyframe-declaration-no-important": true,
              "media-feature-name-no-unknown": true,
              "no-empty-source": true,
              "property-no-unknown": true,
              "selector-pseudo-class-no-unknown": true,
              "selector-type-no-unknown": true,
              "shorthand-property-no-redundant-values": true,
              "unit-no-unknown": true
            }
          }' > .stylelintrc.json
        fi

    - name: Lint HTML
      run: |
        htmlhint "index.html" || {
          echo "HTML linting failed";
          exit 1;
        }

    - name: Lint CSS
      run: |
        stylelint "style.css" || {
          echo "CSS linting failed";
          exit 1;
        }

    - name: Lint JavaScript
      run: |
        jshint "script.js" || {
          echo "JavaScript linting failed";
          exit 1;
        }

    - name: Check for Broken Links
      run: |
        blc http://localhost --follow --exclude linkedin.com || {
          echo "Broken link check failed";
          exit 1;
        }

    - name: Check HTML Validity
      run: |
        vnu-jar --skip-non-html "index.html" || {
          echo "HTML validity check failed";
          exit 1;
        }

    - name: Verify Successful Execution
      run: echo "CI process completed successfully"
