name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install -g htmlhint stylelint jshint broken-link-checker vnu-jar || {
          echo "Dependency installation failed";
          exit 1;
        }

    - name: Lint HTML
      run: |
        htmlhint "index.html" || {
          echo "HTML linting failed";
          exit 1;
        }

    - name: Lint CSS
      run: |
        stylelint "**/*.css" || {
          echo "CSS linting failed";
          exit 1;
        }

    - name: Lint JavaScript
      run: |
        jshint "script.js" || {
          echo "JavaScript linting failed";
          exit 1;
        }

    - name: Check for Broken Links
      run: |
        blc http://localhost --follow --exclude linkedin.com || {
          echo "Broken link check failed";
          exit 1;
        }

    - name: Check HTML Validity
      run: |
        vnu-jar --skip-non-html "index.html" || {
          echo "HTML validity check failed";
          exit 1;
        }

    - name: Verify Successful Execution
      run: echo "CI process completed successfully"
