name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install -g htmlhint stylelint jshint broken-link-checker vnu-jar stylelint-config-standard

    - name: Lint HTML
      run: htmlhint "index.html"

    - name: Lint and fix CSS
      run: stylelint "style.css" --fix
